2021-02-08 15:11:50,541 INFO    MainThread:31285 [wandb_setup.py:_flush():70] setting env: {}
2021-02-08 15:11:50,542 INFO    MainThread:31285 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2021-02-08 15:11:50,542 INFO    MainThread:31285 [wandb_setup.py:_flush():70] setting login settings: {}
2021-02-08 15:11:50,542 INFO    MainThread:31285 [wandb_init.py:_log_setup():318] Logging user logs to /home/pfrod/architectures/wandb/run-20210208_151150-1b3ehdqq/logs/debug.log
2021-02-08 15:11:50,542 INFO    MainThread:31285 [wandb_init.py:_log_setup():319] Logging internal logs to /home/pfrod/architectures/wandb/run-20210208_151150-1b3ehdqq/logs/debug-internal.log
2021-02-08 15:11:53,297 WARNING MainThread:31285 [wandb_init.py:init():709] interrupted
Traceback (most recent call last):
  File "/home/pfrod/anaconda3/envs/env_minus/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 689, in init
    run = wi.init()
  File "/home/pfrod/anaconda3/envs/env_minus/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 469, in init
    _ = backend.interface.communicate_run_start()
  File "/home/pfrod/anaconda3/envs/env_minus/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 647, in communicate_run_start
    result = self._communicate(rec)
  File "/home/pfrod/anaconda3/envs/env_minus/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 465, in _communicate
    f = future.get(timeout)
  File "/home/pfrod/anaconda3/envs/env_minus/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 65, in get
    is_set = self._object_ready.wait(timeout)
  File "/home/pfrod/anaconda3/envs/env_minus/lib/python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "/home/pfrod/anaconda3/envs/env_minus/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2021-02-08 15:11:53,311 INFO    MainThread:31285 [internal.py:handle_exit():139] Internal process exited
